// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: account.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/mezonai/mmn/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountServiceName is the fully-qualified name of the AccountService service.
	AccountServiceName = "mmn.AccountService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountServiceGetAccountProcedure is the fully-qualified name of the AccountService's GetAccount
	// RPC.
	AccountServiceGetAccountProcedure = "/mmn.AccountService/GetAccount"
	// AccountServiceGetCurrentNonceProcedure is the fully-qualified name of the AccountService's
	// GetCurrentNonce RPC.
	AccountServiceGetCurrentNonceProcedure = "/mmn.AccountService/GetCurrentNonce"
)

// AccountServiceClient is a client for the mmn.AccountService service.
type AccountServiceClient interface {
	GetAccount(context.Context, *connect.Request[proto.GetAccountRequest]) (*connect.Response[proto.GetAccountResponse], error)
	GetCurrentNonce(context.Context, *connect.Request[proto.GetCurrentNonceRequest]) (*connect.Response[proto.GetCurrentNonceResponse], error)
}

// NewAccountServiceClient constructs a client for the mmn.AccountService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accountServiceMethods := proto.File_account_proto.Services().ByName("AccountService").Methods()
	return &accountServiceClient{
		getAccount: connect.NewClient[proto.GetAccountRequest, proto.GetAccountResponse](
			httpClient,
			baseURL+AccountServiceGetAccountProcedure,
			connect.WithSchema(accountServiceMethods.ByName("GetAccount")),
			connect.WithClientOptions(opts...),
		),
		getCurrentNonce: connect.NewClient[proto.GetCurrentNonceRequest, proto.GetCurrentNonceResponse](
			httpClient,
			baseURL+AccountServiceGetCurrentNonceProcedure,
			connect.WithSchema(accountServiceMethods.ByName("GetCurrentNonce")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountServiceClient implements AccountServiceClient.
type accountServiceClient struct {
	getAccount      *connect.Client[proto.GetAccountRequest, proto.GetAccountResponse]
	getCurrentNonce *connect.Client[proto.GetCurrentNonceRequest, proto.GetCurrentNonceResponse]
}

// GetAccount calls mmn.AccountService.GetAccount.
func (c *accountServiceClient) GetAccount(ctx context.Context, req *connect.Request[proto.GetAccountRequest]) (*connect.Response[proto.GetAccountResponse], error) {
	return c.getAccount.CallUnary(ctx, req)
}

// GetCurrentNonce calls mmn.AccountService.GetCurrentNonce.
func (c *accountServiceClient) GetCurrentNonce(ctx context.Context, req *connect.Request[proto.GetCurrentNonceRequest]) (*connect.Response[proto.GetCurrentNonceResponse], error) {
	return c.getCurrentNonce.CallUnary(ctx, req)
}

// AccountServiceHandler is an implementation of the mmn.AccountService service.
type AccountServiceHandler interface {
	GetAccount(context.Context, *connect.Request[proto.GetAccountRequest]) (*connect.Response[proto.GetAccountResponse], error)
	GetCurrentNonce(context.Context, *connect.Request[proto.GetCurrentNonceRequest]) (*connect.Response[proto.GetCurrentNonceResponse], error)
}

// NewAccountServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountServiceHandler(svc AccountServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountServiceMethods := proto.File_account_proto.Services().ByName("AccountService").Methods()
	accountServiceGetAccountHandler := connect.NewUnaryHandler(
		AccountServiceGetAccountProcedure,
		svc.GetAccount,
		connect.WithSchema(accountServiceMethods.ByName("GetAccount")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceGetCurrentNonceHandler := connect.NewUnaryHandler(
		AccountServiceGetCurrentNonceProcedure,
		svc.GetCurrentNonce,
		connect.WithSchema(accountServiceMethods.ByName("GetCurrentNonce")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mmn.AccountService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountServiceGetAccountProcedure:
			accountServiceGetAccountHandler.ServeHTTP(w, r)
		case AccountServiceGetCurrentNonceProcedure:
			accountServiceGetCurrentNonceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountServiceHandler struct{}

func (UnimplementedAccountServiceHandler) GetAccount(context.Context, *connect.Request[proto.GetAccountRequest]) (*connect.Response[proto.GetAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mmn.AccountService.GetAccount is not implemented"))
}

func (UnimplementedAccountServiceHandler) GetCurrentNonce(context.Context, *connect.Request[proto.GetCurrentNonceRequest]) (*connect.Response[proto.GetCurrentNonceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mmn.AccountService.GetCurrentNonce is not implemented"))
}
