// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: block.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/mezonai/mmn/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BlockServiceName is the fully-qualified name of the BlockService service.
	BlockServiceName = "mmn.BlockService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BlockServiceGetBlockNumberProcedure is the fully-qualified name of the BlockService's
	// GetBlockNumber RPC.
	BlockServiceGetBlockNumberProcedure = "/mmn.BlockService/GetBlockNumber"
	// BlockServiceGetBlockByNumberProcedure is the fully-qualified name of the BlockService's
	// GetBlockByNumber RPC.
	BlockServiceGetBlockByNumberProcedure = "/mmn.BlockService/GetBlockByNumber"
	// BlockServiceGetBlockByRangeProcedure is the fully-qualified name of the BlockService's
	// GetBlockByRange RPC.
	BlockServiceGetBlockByRangeProcedure = "/mmn.BlockService/GetBlockByRange"
)

// BlockServiceClient is a client for the mmn.BlockService service.
type BlockServiceClient interface {
	GetBlockNumber(context.Context, *connect.Request[proto.EmptyParams]) (*connect.Response[proto.GetBlockNumberResponse], error)
	GetBlockByNumber(context.Context, *connect.Request[proto.GetBlockByNumberRequest]) (*connect.Response[proto.GetBlockByNumberResponse], error)
	GetBlockByRange(context.Context, *connect.Request[proto.GetBlockByRangeRequest]) (*connect.Response[proto.GetBlockByRangeResponse], error)
}

// NewBlockServiceClient constructs a client for the mmn.BlockService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBlockServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BlockServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	blockServiceMethods := proto.File_block_proto.Services().ByName("BlockService").Methods()
	return &blockServiceClient{
		getBlockNumber: connect.NewClient[proto.EmptyParams, proto.GetBlockNumberResponse](
			httpClient,
			baseURL+BlockServiceGetBlockNumberProcedure,
			connect.WithSchema(blockServiceMethods.ByName("GetBlockNumber")),
			connect.WithClientOptions(opts...),
		),
		getBlockByNumber: connect.NewClient[proto.GetBlockByNumberRequest, proto.GetBlockByNumberResponse](
			httpClient,
			baseURL+BlockServiceGetBlockByNumberProcedure,
			connect.WithSchema(blockServiceMethods.ByName("GetBlockByNumber")),
			connect.WithClientOptions(opts...),
		),
		getBlockByRange: connect.NewClient[proto.GetBlockByRangeRequest, proto.GetBlockByRangeResponse](
			httpClient,
			baseURL+BlockServiceGetBlockByRangeProcedure,
			connect.WithSchema(blockServiceMethods.ByName("GetBlockByRange")),
			connect.WithClientOptions(opts...),
		),
	}
}

// blockServiceClient implements BlockServiceClient.
type blockServiceClient struct {
	getBlockNumber   *connect.Client[proto.EmptyParams, proto.GetBlockNumberResponse]
	getBlockByNumber *connect.Client[proto.GetBlockByNumberRequest, proto.GetBlockByNumberResponse]
	getBlockByRange  *connect.Client[proto.GetBlockByRangeRequest, proto.GetBlockByRangeResponse]
}

// GetBlockNumber calls mmn.BlockService.GetBlockNumber.
func (c *blockServiceClient) GetBlockNumber(ctx context.Context, req *connect.Request[proto.EmptyParams]) (*connect.Response[proto.GetBlockNumberResponse], error) {
	return c.getBlockNumber.CallUnary(ctx, req)
}

// GetBlockByNumber calls mmn.BlockService.GetBlockByNumber.
func (c *blockServiceClient) GetBlockByNumber(ctx context.Context, req *connect.Request[proto.GetBlockByNumberRequest]) (*connect.Response[proto.GetBlockByNumberResponse], error) {
	return c.getBlockByNumber.CallUnary(ctx, req)
}

// GetBlockByRange calls mmn.BlockService.GetBlockByRange.
func (c *blockServiceClient) GetBlockByRange(ctx context.Context, req *connect.Request[proto.GetBlockByRangeRequest]) (*connect.Response[proto.GetBlockByRangeResponse], error) {
	return c.getBlockByRange.CallUnary(ctx, req)
}

// BlockServiceHandler is an implementation of the mmn.BlockService service.
type BlockServiceHandler interface {
	GetBlockNumber(context.Context, *connect.Request[proto.EmptyParams]) (*connect.Response[proto.GetBlockNumberResponse], error)
	GetBlockByNumber(context.Context, *connect.Request[proto.GetBlockByNumberRequest]) (*connect.Response[proto.GetBlockByNumberResponse], error)
	GetBlockByRange(context.Context, *connect.Request[proto.GetBlockByRangeRequest]) (*connect.Response[proto.GetBlockByRangeResponse], error)
}

// NewBlockServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBlockServiceHandler(svc BlockServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	blockServiceMethods := proto.File_block_proto.Services().ByName("BlockService").Methods()
	blockServiceGetBlockNumberHandler := connect.NewUnaryHandler(
		BlockServiceGetBlockNumberProcedure,
		svc.GetBlockNumber,
		connect.WithSchema(blockServiceMethods.ByName("GetBlockNumber")),
		connect.WithHandlerOptions(opts...),
	)
	blockServiceGetBlockByNumberHandler := connect.NewUnaryHandler(
		BlockServiceGetBlockByNumberProcedure,
		svc.GetBlockByNumber,
		connect.WithSchema(blockServiceMethods.ByName("GetBlockByNumber")),
		connect.WithHandlerOptions(opts...),
	)
	blockServiceGetBlockByRangeHandler := connect.NewUnaryHandler(
		BlockServiceGetBlockByRangeProcedure,
		svc.GetBlockByRange,
		connect.WithSchema(blockServiceMethods.ByName("GetBlockByRange")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mmn.BlockService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BlockServiceGetBlockNumberProcedure:
			blockServiceGetBlockNumberHandler.ServeHTTP(w, r)
		case BlockServiceGetBlockByNumberProcedure:
			blockServiceGetBlockByNumberHandler.ServeHTTP(w, r)
		case BlockServiceGetBlockByRangeProcedure:
			blockServiceGetBlockByRangeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBlockServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBlockServiceHandler struct{}

func (UnimplementedBlockServiceHandler) GetBlockNumber(context.Context, *connect.Request[proto.EmptyParams]) (*connect.Response[proto.GetBlockNumberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mmn.BlockService.GetBlockNumber is not implemented"))
}

func (UnimplementedBlockServiceHandler) GetBlockByNumber(context.Context, *connect.Request[proto.GetBlockByNumberRequest]) (*connect.Response[proto.GetBlockByNumberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mmn.BlockService.GetBlockByNumber is not implemented"))
}

func (UnimplementedBlockServiceHandler) GetBlockByRange(context.Context, *connect.Request[proto.GetBlockByRangeRequest]) (*connect.Response[proto.GetBlockByRangeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mmn.BlockService.GetBlockByRange is not implemented"))
}
