// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: health.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/mezonai/mmn/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HealthServiceName is the fully-qualified name of the HealthService service.
	HealthServiceName = "mmn.HealthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthServiceCheckProcedure is the fully-qualified name of the HealthService's Check RPC.
	HealthServiceCheckProcedure = "/mmn.HealthService/Check"
	// HealthServiceWatchProcedure is the fully-qualified name of the HealthService's Watch RPC.
	HealthServiceWatchProcedure = "/mmn.HealthService/Watch"
)

// HealthServiceClient is a client for the mmn.HealthService service.
type HealthServiceClient interface {
	// Basic health check
	Check(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.HealthCheckResponse], error)
	// Stream continuous health status
	Watch(context.Context, *connect.Request[proto.Empty]) (*connect.ServerStreamForClient[proto.HealthCheckResponse], error)
}

// NewHealthServiceClient constructs a client for the mmn.HealthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	healthServiceMethods := proto.File_health_proto.Services().ByName("HealthService").Methods()
	return &healthServiceClient{
		check: connect.NewClient[proto.Empty, proto.HealthCheckResponse](
			httpClient,
			baseURL+HealthServiceCheckProcedure,
			connect.WithSchema(healthServiceMethods.ByName("Check")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[proto.Empty, proto.HealthCheckResponse](
			httpClient,
			baseURL+HealthServiceWatchProcedure,
			connect.WithSchema(healthServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthServiceClient implements HealthServiceClient.
type healthServiceClient struct {
	check *connect.Client[proto.Empty, proto.HealthCheckResponse]
	watch *connect.Client[proto.Empty, proto.HealthCheckResponse]
}

// Check calls mmn.HealthService.Check.
func (c *healthServiceClient) Check(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.Response[proto.HealthCheckResponse], error) {
	return c.check.CallUnary(ctx, req)
}

// Watch calls mmn.HealthService.Watch.
func (c *healthServiceClient) Watch(ctx context.Context, req *connect.Request[proto.Empty]) (*connect.ServerStreamForClient[proto.HealthCheckResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// HealthServiceHandler is an implementation of the mmn.HealthService service.
type HealthServiceHandler interface {
	// Basic health check
	Check(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.HealthCheckResponse], error)
	// Stream continuous health status
	Watch(context.Context, *connect.Request[proto.Empty], *connect.ServerStream[proto.HealthCheckResponse]) error
}

// NewHealthServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthServiceHandler(svc HealthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthServiceMethods := proto.File_health_proto.Services().ByName("HealthService").Methods()
	healthServiceCheckHandler := connect.NewUnaryHandler(
		HealthServiceCheckProcedure,
		svc.Check,
		connect.WithSchema(healthServiceMethods.ByName("Check")),
		connect.WithHandlerOptions(opts...),
	)
	healthServiceWatchHandler := connect.NewServerStreamHandler(
		HealthServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(healthServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mmn.HealthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthServiceCheckProcedure:
			healthServiceCheckHandler.ServeHTTP(w, r)
		case HealthServiceWatchProcedure:
			healthServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthServiceHandler struct{}

func (UnimplementedHealthServiceHandler) Check(context.Context, *connect.Request[proto.Empty]) (*connect.Response[proto.HealthCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mmn.HealthService.Check is not implemented"))
}

func (UnimplementedHealthServiceHandler) Watch(context.Context, *connect.Request[proto.Empty], *connect.ServerStream[proto.HealthCheckResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mmn.HealthService.Watch is not implemented"))
}
