// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tx.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/mezonai/mmn/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TxServiceName is the fully-qualified name of the TxService service.
	TxServiceName = "mmn.TxService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TxServiceAddTxProcedure is the fully-qualified name of the TxService's AddTx RPC.
	TxServiceAddTxProcedure = "/mmn.TxService/AddTx"
	// TxServiceGetTxByHashProcedure is the fully-qualified name of the TxService's GetTxByHash RPC.
	TxServiceGetTxByHashProcedure = "/mmn.TxService/GetTxByHash"
	// TxServiceSubscribeTransactionStatusProcedure is the fully-qualified name of the TxService's
	// SubscribeTransactionStatus RPC.
	TxServiceSubscribeTransactionStatusProcedure = "/mmn.TxService/SubscribeTransactionStatus"
	// TxServiceGetPendingTransactionsProcedure is the fully-qualified name of the TxService's
	// GetPendingTransactions RPC.
	TxServiceGetPendingTransactionsProcedure = "/mmn.TxService/GetPendingTransactions"
)

// TxServiceClient is a client for the mmn.TxService service.
type TxServiceClient interface {
	AddTx(context.Context, *connect.Request[proto.SignedTxMsg]) (*connect.Response[proto.AddTxResponse], error)
	GetTxByHash(context.Context, *connect.Request[proto.GetTxByHashRequest]) (*connect.Response[proto.GetTxByHashResponse], error)
	SubscribeTransactionStatus(context.Context, *connect.Request[proto.SubscribeTransactionStatusRequest]) (*connect.ServerStreamForClient[proto.TransactionStatusInfo], error)
	GetPendingTransactions(context.Context, *connect.Request[proto.GetPendingTransactionsRequest]) (*connect.Response[proto.GetPendingTransactionsResponse], error)
}

// NewTxServiceClient constructs a client for the mmn.TxService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTxServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TxServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	txServiceMethods := proto.File_tx_proto.Services().ByName("TxService").Methods()
	return &txServiceClient{
		addTx: connect.NewClient[proto.SignedTxMsg, proto.AddTxResponse](
			httpClient,
			baseURL+TxServiceAddTxProcedure,
			connect.WithSchema(txServiceMethods.ByName("AddTx")),
			connect.WithClientOptions(opts...),
		),
		getTxByHash: connect.NewClient[proto.GetTxByHashRequest, proto.GetTxByHashResponse](
			httpClient,
			baseURL+TxServiceGetTxByHashProcedure,
			connect.WithSchema(txServiceMethods.ByName("GetTxByHash")),
			connect.WithClientOptions(opts...),
		),
		subscribeTransactionStatus: connect.NewClient[proto.SubscribeTransactionStatusRequest, proto.TransactionStatusInfo](
			httpClient,
			baseURL+TxServiceSubscribeTransactionStatusProcedure,
			connect.WithSchema(txServiceMethods.ByName("SubscribeTransactionStatus")),
			connect.WithClientOptions(opts...),
		),
		getPendingTransactions: connect.NewClient[proto.GetPendingTransactionsRequest, proto.GetPendingTransactionsResponse](
			httpClient,
			baseURL+TxServiceGetPendingTransactionsProcedure,
			connect.WithSchema(txServiceMethods.ByName("GetPendingTransactions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// txServiceClient implements TxServiceClient.
type txServiceClient struct {
	addTx                      *connect.Client[proto.SignedTxMsg, proto.AddTxResponse]
	getTxByHash                *connect.Client[proto.GetTxByHashRequest, proto.GetTxByHashResponse]
	subscribeTransactionStatus *connect.Client[proto.SubscribeTransactionStatusRequest, proto.TransactionStatusInfo]
	getPendingTransactions     *connect.Client[proto.GetPendingTransactionsRequest, proto.GetPendingTransactionsResponse]
}

// AddTx calls mmn.TxService.AddTx.
func (c *txServiceClient) AddTx(ctx context.Context, req *connect.Request[proto.SignedTxMsg]) (*connect.Response[proto.AddTxResponse], error) {
	return c.addTx.CallUnary(ctx, req)
}

// GetTxByHash calls mmn.TxService.GetTxByHash.
func (c *txServiceClient) GetTxByHash(ctx context.Context, req *connect.Request[proto.GetTxByHashRequest]) (*connect.Response[proto.GetTxByHashResponse], error) {
	return c.getTxByHash.CallUnary(ctx, req)
}

// SubscribeTransactionStatus calls mmn.TxService.SubscribeTransactionStatus.
func (c *txServiceClient) SubscribeTransactionStatus(ctx context.Context, req *connect.Request[proto.SubscribeTransactionStatusRequest]) (*connect.ServerStreamForClient[proto.TransactionStatusInfo], error) {
	return c.subscribeTransactionStatus.CallServerStream(ctx, req)
}

// GetPendingTransactions calls mmn.TxService.GetPendingTransactions.
func (c *txServiceClient) GetPendingTransactions(ctx context.Context, req *connect.Request[proto.GetPendingTransactionsRequest]) (*connect.Response[proto.GetPendingTransactionsResponse], error) {
	return c.getPendingTransactions.CallUnary(ctx, req)
}

// TxServiceHandler is an implementation of the mmn.TxService service.
type TxServiceHandler interface {
	AddTx(context.Context, *connect.Request[proto.SignedTxMsg]) (*connect.Response[proto.AddTxResponse], error)
	GetTxByHash(context.Context, *connect.Request[proto.GetTxByHashRequest]) (*connect.Response[proto.GetTxByHashResponse], error)
	SubscribeTransactionStatus(context.Context, *connect.Request[proto.SubscribeTransactionStatusRequest], *connect.ServerStream[proto.TransactionStatusInfo]) error
	GetPendingTransactions(context.Context, *connect.Request[proto.GetPendingTransactionsRequest]) (*connect.Response[proto.GetPendingTransactionsResponse], error)
}

// NewTxServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTxServiceHandler(svc TxServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	txServiceMethods := proto.File_tx_proto.Services().ByName("TxService").Methods()
	txServiceAddTxHandler := connect.NewUnaryHandler(
		TxServiceAddTxProcedure,
		svc.AddTx,
		connect.WithSchema(txServiceMethods.ByName("AddTx")),
		connect.WithHandlerOptions(opts...),
	)
	txServiceGetTxByHashHandler := connect.NewUnaryHandler(
		TxServiceGetTxByHashProcedure,
		svc.GetTxByHash,
		connect.WithSchema(txServiceMethods.ByName("GetTxByHash")),
		connect.WithHandlerOptions(opts...),
	)
	txServiceSubscribeTransactionStatusHandler := connect.NewServerStreamHandler(
		TxServiceSubscribeTransactionStatusProcedure,
		svc.SubscribeTransactionStatus,
		connect.WithSchema(txServiceMethods.ByName("SubscribeTransactionStatus")),
		connect.WithHandlerOptions(opts...),
	)
	txServiceGetPendingTransactionsHandler := connect.NewUnaryHandler(
		TxServiceGetPendingTransactionsProcedure,
		svc.GetPendingTransactions,
		connect.WithSchema(txServiceMethods.ByName("GetPendingTransactions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mmn.TxService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TxServiceAddTxProcedure:
			txServiceAddTxHandler.ServeHTTP(w, r)
		case TxServiceGetTxByHashProcedure:
			txServiceGetTxByHashHandler.ServeHTTP(w, r)
		case TxServiceSubscribeTransactionStatusProcedure:
			txServiceSubscribeTransactionStatusHandler.ServeHTTP(w, r)
		case TxServiceGetPendingTransactionsProcedure:
			txServiceGetPendingTransactionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTxServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTxServiceHandler struct{}

func (UnimplementedTxServiceHandler) AddTx(context.Context, *connect.Request[proto.SignedTxMsg]) (*connect.Response[proto.AddTxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mmn.TxService.AddTx is not implemented"))
}

func (UnimplementedTxServiceHandler) GetTxByHash(context.Context, *connect.Request[proto.GetTxByHashRequest]) (*connect.Response[proto.GetTxByHashResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mmn.TxService.GetTxByHash is not implemented"))
}

func (UnimplementedTxServiceHandler) SubscribeTransactionStatus(context.Context, *connect.Request[proto.SubscribeTransactionStatusRequest], *connect.ServerStream[proto.TransactionStatusInfo]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mmn.TxService.SubscribeTransactionStatus is not implemented"))
}

func (UnimplementedTxServiceHandler) GetPendingTransactions(context.Context, *connect.Request[proto.GetPendingTransactionsRequest]) (*connect.Response[proto.GetPendingTransactionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mmn.TxService.GetPendingTransactions is not implemented"))
}
