# golangci-lint configuration file
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused

    - goconst
    - gocritic
    - gocyclo
    - misspell
    - unconvert
    - unparam
    - whitespace

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (*db.DatabaseBatch).Close
      # Display function signature instead of selector.
      verbose: true

    govet:
      enable: 
        - shadow

    staticcheck:
      checks: ["all"]

    gocyclo:
      min-complexity: 15

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style

    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US

  exclusions:
    paths:
      - client_test
      - mezon-migration
      - ".*_test\\.go$"
      - ".*\\.pb\\.go$"
      - ".*\\.grpc\\.pb\\.go$"

    rules:
      - path: ".*\\.pb\\.go$"
        linters:
          - all

      - path: ".*\\.grpc\\.pb\\.go$"
        linters:
          - all

      # Exclude client_test and mezon-migration directories
      - path: "^client_test/.*"
        linters:
          - all

      - path: "^mezon-migration/.*"
        linters:
          - all

      # Exclude some linters from test files
      - path: "_test\\.go$"
        linters:
          - gocyclo
          - gosec
          
issues:
  max-issues-per-linter: 0
  max-same-issues: 0