# golangci-lint configuration file
# https://golangci-lint.run/usage/configuration/
version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused

    - goconst
    - gocritic
    - gocyclo
    - misspell
    - unconvert
    - unparam
    - whitespace

  disable:
    - errcheck

  exclusions:
    paths:
      - client_test
      - mezon-migration
      - ".*_test\\.go$"
      - ".*\\.pb\\.go$"
      - ".*\\.grpc\\.pb\\.go$"

linters-settings:
  govet:
    check-shadowing: true

  staticcheck:
    checks: ["all"]

  unused:
    check-exported: false

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  goconst:
    min-len: 2
    min-occurrences: 2


  misspell:
    locale: US


issues:
  exclude-rules:
    # Exclude protobuf generated files
    - path: ".*\\.pb\\.go$"
      linters:
        - all

    - path: ".*\\.grpc\\.pb\\.go$"
      linters:
        - all

    # Exclude client_test and mezon-migration directories
    - path: "^client_test/.*"
      linters:
        - all

    - path: "^mezon-migration/.*"
      linters:
        - all

    # Exclude some linters from test files
    - path: "_test\\.go$"
      linters:
        - gocyclo
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false