services:
  node1:
    build: .
    container_name: node1
    command: ["./mmn", "run", "--node", "node1"]
    ports:
      - "8001:8001"
      - "9001:9001"
    networks:
      - mezon
    restart: always
  node2:
    build: .
    container_name: node2
    command: ["./mmn", "run", "--node", "node2"]
    ports:
      - "8002:8002"
      - "9002:9002"
    networks:
      - mezon
    restart: always


  node3:
    build: .
    container_name: node3
    command: ["./mmn", "run", "--node", "node3"]
    ports:
      - "8003:8003"
      - "9003:9003"
    networks:
      - mezon
    restart: always

networks:
  mezon:
