version: "3.8"

services:
  bootnode:
    build:
      context: .
      args:
        DATABASE: leveldb  #
    image: mmn-node:leveldb
    container_name: bootnode
    command: ["./mmn", "bootnode", "--bootstrap-p2p-port", "9000", "--privkey-path", "./config/bootnode_privkey.txt"]
    ports:
      - "9000:9000"
    networks:
      - mezon
    restart: unless-stopped
  node1:
    build:
      context: .
      args:
        DATABASE: rocksdb
    image: mmn-node:rocksdb
    container_name: node1
    command:
      [
        "./mmn", "node",
        "--database", "rocksdb",
        "--privkey-path", "config/key1.txt",
        "--listen-addr", ":8001",
        "--grpc-addr", ":9001",
        "--bootstrap-addresses", "/dns4/bootnode/tcp/9000/p2p/12D3KooWAhZyyZV2KBtfm8zsLaKPvcmVfaYczJ5UdpB8cJU7vKg2"
      ]
    depends_on:
      - bootnode
    ports:
      - "8001:8001"
      - "9001:9001"
    networks:
      - mezon
    restart: unless-stopped
  node2:
    image: mmn-node:rocksdb
    container_name: node2
    command:
      [
        "./mmn", "node",
        "--database", "rocksdb",
        "--privkey-path", "config/key2.txt",
        "--listen-addr", ":8002",
        "--grpc-addr", ":9002",
        "--bootstrap-addresses", "/dns4/bootnode/tcp/9000/p2p/12D3KooWAhZyyZV2KBtfm8zsLaKPvcmVfaYczJ5UdpB8cJU7vKg2"
      ]
    depends_on:
      - bootnode
    ports:
      - "8002:8002"
      - "9002:9002"
    networks:
      - mezon
    restart: unless-stopped

  node3:
    image: mmn-node:rocksdb
    container_name: node3
    command:
      [
        "./mmn", "node",
        "--database", "rocksdb",
        "--privkey-path", "config/key3.txt",
        "--listen-addr", ":8003",
        "--grpc-addr", ":9003",
        "--bootstrap-addresses", "/dns4/bootnode/tcp/9000/p2p/12D3KooWAhZyyZV2KBtfm8zsLaKPvcmVfaYczJ5UdpB8cJU7vKg2"
      ]
    depends_on:
      - bootnode
    ports:
      - "8003:8003"
      - "9003:9003"
    networks:
      - mezon
    restart: unless-stopped
networks:
  mezon:
