version: "3.8"

services:
  bootnode:
    build:
      context: .
      args:
        DB_VENDOR: ${DB_VENDOR:-rocksdb}  #rocksdb or leveldb
    image: mmn-node:${DB_VENDOR:-rocksdb}
    container_name: bootnode
    command: ["./mmn", "bootnode", "--bootstrap-p2p-port", "9000", "--privkey-path", "./config/bootnode_privkey.txt"]
    ports:
      - "9000:9000"
    networks:
      - mezon
    restart: unless-stopped
  node1:
    image: mmn-node:${DB_VENDOR:-rocksdb}
    container_name: node1
    command: >
      sh -c '
        rm -rf ./node-data/node1 &&
        ./mmn init --data-dir "./node-data/node1" --genesis "config/genesis.yml" --database "${DB_VENDOR:-rocksdb}" --privkey-path "config/key1.txt" &&
        ./mmn node --database ${DB_VENDOR:-rocksdb} --data-dir "./node-data/node1" --listen-addr ":8001" --jsonrpc-addr ":8080" --grpc-addr ":9001" --bootstrap-addresses "/dns4/bootnode/tcp/9000/p2p/12D3KooWAhZyyZV2KBtfm8zsLaKPvcmVfaYczJ5UdpB8cJU7vKg2"
      '
    depends_on:
      - bootnode
    ports:
      - "8001:8001"
      - "8080:8080"
      - "9001:9001"
    volumes:
      - node_data:/app/node-data
    networks:
      - mezon
    restart: unless-stopped
    environment:
      CORS_ALLOWED_ORIGINS: http://127.0.0.1:4200
      CORS_ALLOWED_METHODS: GET,POST,OPTIONS
      CORS_ALLOWED_HEADERS: Content-Type,Authorization,X-Requested-With
      CORS_MAX_AGE: 86400
  node2:
    image: mmn-node:${DB_VENDOR:-rocksdb}
    container_name: node2
    command: >
      sh -c '
        rm -rf ./node-data/node2 &&
        ./mmn init --data-dir "./node-data/node2" --genesis "config/genesis.yml" --database "${DB_VENDOR:-rocksdb}" --privkey-path "config/key2.txt" &&
        ./mmn node --database ${DB_VENDOR:-rocksdb} --data-dir "./node-data/node2" --listen-addr ":8002" --jsonrpc-addr ":8081" --grpc-addr ":9002" --bootstrap-addresses "/dns4/bootnode/tcp/9000/p2p/12D3KooWAhZyyZV2KBtfm8zsLaKPvcmVfaYczJ5UdpB8cJU7vKg2"
      '
    depends_on:
      - bootnode
    ports:
      - "8002:8002"
      - "8081:8081"
      - "9002:9002"
    volumes:
      - node_data:/app/node-data
    networks:
      - mezon
    restart: unless-stopped
    environment:
      CORS_ALLOWED_ORIGINS: http://127.0.0.1:4200
      CORS_ALLOWED_METHODS: GET,POST,OPTIONS
      CORS_ALLOWED_HEADERS: Content-Type,Authorization,X-Requested-With
      CORS_MAX_AGE: 86400
  node3:
    image: mmn-node:${DB_VENDOR:-rocksdb}
    container_name: node3
    command: >
      sh -c '
        rm -rf ./node-data/node3 &&
        ./mmn init --data-dir "./node-data/node3" --genesis "config/genesis.yml" --database "${DB_VENDOR:-rocksdb}" --privkey-path "config/key3.txt" &&
        ./mmn node --database ${DB_VENDOR:-rocksdb} --data-dir "./node-data/node3" --listen-addr ":8003" --jsonrpc-addr ":8082" --grpc-addr ":9003" --bootstrap-addresses "/dns4/bootnode/tcp/9000/p2p/12D3KooWAhZyyZV2KBtfm8zsLaKPvcmVfaYczJ5UdpB8cJU7vKg2"
      '
    depends_on:
      - bootnode
    ports:
      - "8003:8003"
      - "8082:8082"
      - "9003:9003"
    volumes:
      - node_data:/app/node-data
    networks:
      - mezon
    restart: unless-stopped
    environment:
      CORS_ALLOWED_ORIGINS: http://127.0.0.1:4200
      CORS_ALLOWED_METHODS: GET,POST,OPTIONS
      CORS_ALLOWED_HEADERS: Content-Type,Authorization,X-Requested-With
      CORS_MAX_AGE: 86400
networks:
  mezon:
volumes:
  node_data: