version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: mezon
      POSTGRES_PASSWORD: m3z0n
      POSTGRES_DB: mezon
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: