global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: prometheus
    scrape_interval: 1m
    static_configs:
      - targets: ["__TARGET_PROMETHEUS_PORT__"]

  - job_name: mmn-node
    scrape_interval: 5s
    file_sd_configs:
      - files: ["/etc/prometheus/targets/nodes.yml"]