server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "__URL_LOKI_PUSH__"
  # - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: mmn
    static_configs:
      - targets: [localhost]
        labels:
          job: mmn
          __path__: /var/log/mmn/*.log*
    pipeline_stages:
      # extract service name from log filename
      - regex:
          source: filename
          expression: '.*/(?P<node>[a-zA-Z0-9_-]+?)(?:-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}(?:-\d{2}(?:\.\d+)?)?)?\.log(?:\.gz)?$'
      - labels:
          node:

      # extract log level from log line
      - regex:
          expression: '\[(?P<level>[A-Z]+)\]'
      - template:
          source: level
          template: '{{ ToLower .Value }}'
      - labels:
          level:

  - job_name: indexer
    static_configs:
      - targets:
          - localhost
        labels:
          job: indexer
          __path__: /opt/indexer/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: message
            component: component
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          component: