global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: prometheus
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: mmn-node
    scrape_interval: 5s
    file_sd_configs:
      - files: ["/etc/prometheus/targets/nodes.yml"]

  - job_name: node_exporter
    scrape_interval: 15s
    static_configs:
      - targets: ["__PORT_NODE_EXPORTER__"]
        labels:
          node: node1

rule_files:
  - "/etc/prometheus/rules/*.yml"