{
 "title": "MMN Blockchain Nodes",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg by (node) (rate(node_cpu_seconds_total{mode=\"idle\", node=~\"$node\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{node=~\"$node\"}) / node_memory_MemTotal_bytes{node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "System Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - (sum by (node) (node_filesystem_avail_bytes{node=~\"$node\",fstype!=\"tmpfs\",fstype!=\"overlay\"}) / sum by (node) (node_filesystem_size_bytes{node=~\"$node\",fstype!=\"tmpfs\",fstype!=\"overlay\"}))))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mmn_node_mempool_size{node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Average Transaction Finalization Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(mmn_node_tx_finalization_time_sum{node=~\"$node\"}[5m]) / rate(mmn_node_tx_finalization_time_count{node=~\"$node\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}