config:
  faucet:
    address: "faucet_address"
    amount: 1000000000000000000
  self_node:
    pubkey: "pubkey"
    privkey_path: "privkey_path"
    listen_addr: "listen_addr"
    libp2p_addr: "libp2p_addr"
    grpc_addr: "grpc_addr"

  peer_nodes:
    - pubkey: "pubkey1"
      grpc_addr: "grpc_addr1"
      libp2p_addr: "libp2p_addr1"
    - pubkey: "pubkey2"
      grpc_addr: "grpc_addr2"
      libp2p_addr: "libp2p_addr2"
    - pubkey: "pubkey3"
      grpc_addr: "grpc_addr3"
      libp2p_addr: "libp2p_addr3"

  leader_schedule:
    - start_slot: start_slot
      end_slot: end_slot
      leader: "leader1"
    - start_slot: start_slot
      end_slot: end_slot
      leader: "leader2"
    - start_slot: start_slot
      end_slot: end_slot
      leader: "leader3"
