config:
  # Dynamic PoS - no hardcode leader schedule
  leader_schedule: []
  
  # Faucet configuration
  faucet:
    address: "0d1dfad29c20c13dccff213f52d2f98a395a0224b5159628d2bdb077cf4026a7"
    amount: 1000000000000  # 1 trillion tokens for testing

  # Proof of History configuration
  poh:
    hashes_per_tick: 2          # VERY FAST for testing
    ticks_per_slot: 4           # Reduced slot size  
    tick_interval_ms: 400  # 400ms slots

  # Mempool configuration
  mempool:
    max_txs: 10000

  # Validator configuration
  validator:
    batch_size: 100
    leader_timeout: 5000
    leader_timeout_loop_interval: 1000

  # Staking configuration
  staking:
    enabled: true
    slots_per_epoch: 8640        # ~1 hour epochs at 400ms slots
    min_stake_amount: "1000000"  # 1 million tokens minimum stake
    max_validators: 1000         # Maximum number of validators
    epoch_reward_amount: "100000000"  # 100 million tokens per epoch
    unstake_cooldown: 432000     # ~3 days unstaking cooldown
    activation_delay: 8640       # ~1 hour activation delay

  # Dynamic validator configuration - nodes auto-register when they have balance
  genesis_validators: []  # Empty - validators will register themselves dynamically

  # NOTE: leader_schedule is now REMOVED - using dynamic PoS-based scheduling  
  # Leader schedule is automatically generated based on active node validators
