config:
  leader_schedule:
    - start_slot: 1
      end_slot: 10
      leader: "89y4uNijxzE9xXNvhU5oCbEN2RhSPCPQUwrJy7bPZPf8" # node 1/key1
  alloc: # support array
    addresses: 
      - address: "tCpERuK8HdBMFVShya49pgfBFVyxbzzgDp7EKKE2Nx6"
        amount: 100000000000000000
  poh:
    hashes_per_tick: 10
    ticks_per_slot: 4
    tick_interval_ms: 100
  mempool:
    max_txs: 100000
  validator:
    batch_size: 750
    leader_timeout: 50
    leader_timeout_loop_interval: 5
  native_currency:
    decimals: 6
