config:
  leader_schedule:
    - start_slot: 1
      end_slot: 100
      leader: "6a4dd9b6efe0fc8f125be331735b0e33239e24f02c84e555ade9ea50bd1369db" # node 1/key1
    - start_slot: 101
      end_slot: 200
      leader: "650b1d76a0e9f0e57b44c4bf6342f7e4b511d9b1310f7898129c90abca296248" # node 2/key2
    - start_slot: 201
      end_slot: 3000000000
      leader: "066c7311f0f02057565bc1c4133ac3d009e9474ea90daa89ec9cf89d289d8e9b" # node 3/key3
  alloc: # support array
    addresses: 
      - address: "0d1dfad29c20c13dccff213f52d2f98a395a0224b5159628d2bdb077cf4026a7"
        amount: 2000000000
  poh:
    hashes_per_tick: 10
    ticks_per_slot: 4
    tick_interval_ms: 100
  mempool:
    max_txs: 100000
  validator:
    batch_size: 750
    leader_timeout: 50
    leader_timeout_loop_interval: 5
  access_control:
    allowlist_enabled: false
    blacklist_enabled: false
    allowed_peers: []
    blacklisted_peers: []