config:
  leader_schedule:
    - start_slot: 1
      end_slot: 10
      leader: "89y4uNijxzE9xXNvhU5oCbEN2RhSPCPQUwrJy7bPZPf8" # node 1/key1
      bls_pubkey: "a226b0717920d3ceda799f924248e8ec59156d649b121fa7940cc5dd0ea90074ae2496c6514008e76be980b3368347fc"
    - start_slot: 11
      end_slot: 20
      leader: "7oS1SxgwUTLTfxDqboRMdPYYBVxsc9xSq2Q2nM9VjssV" # node 2/key2
      bls_pubkey: "80003176420354717c1e3e9393797cba8d386ffcbdb9de6dcc38e9bfc4dcd7fa2c56fa0b4ff2e323de03a35c4afb6c3a"
    - start_slot: 21
      end_slot: 30
      leader: "S5MrFRhc92vmczcrDpNG8CLoDPh2jZH8f6Na11bFyDt" # node 3/key3
      bls_pubkey: "9912d220fc786775b672589cc3413716ca8aafe672783e3e6af514b46b36101db184c814f51f982d55754c8eb27a3fa9"
  alloc: # support array
    addresses: 
      - address: "tCpERuK8HdBMFVShya49pgfBFVyxbzzgDp7EKKE2Nx6"
        amount: 100000000000000000
  poh:
    hashes_per_tick: 10
    ticks_per_slot: 4
    tick_interval_ms: 100
  mempool:
    max_txs: 100000
  validator:
    batch_size: 750
    leader_timeout: 50
    leader_timeout_loop_interval: 5
  native_currency:
    decimals: 6  