config:
  dynamic_leader_scheduler:
    enabled: true
    slots_per_epoch: 432
    max_consecutive_slots: 4  # Maximum consecutive slots per leader
    validators: []  # Dynamic validators will be registered when nodes join
    total_stake: 0  # Will be calculated dynamically
    voting_threshold: 0.67  # 2/3 supermajority
  alloc: # support array
    addresses: 
      - address: "tCpERuK8HdBMFVShya49pgfBFVyxbzzgDp7EKKE2Nx6"
        amount: 2000000000
  poh:
    poh_auto_hash_interval: 10
    hashes_per_tick: 10
    ticks_per_slot: 4
    tick_interval_ms: 100
  mempool:
    max_txs: 100000
  validator:
    batch_size: 750
    leader_timeout: 50
    leader_timeout_loop_interval: 5