config:
  leader_schedule:
    - start_slot: 1
      end_slot: 100
      leader: "89y4uNijxzE9xXNvhU5oCbEN2RhSPCPQUwrJy7bPZPf8" # node 1/key1
    - start_slot: 101
      end_slot: 200
      leader: "7oS1SxgwUTLTfxDqboRMdPYYBVxsc9xSq2Q2nM9VjssV" # node 2/key2
    - start_slot: 201
      end_slot: 3000000000
      leader: "S5MrFRhc92vmczcrDpNG8CLoDPh2jZH8f6Na11bFyDt" # node 3/key3
  alloc: # support array
    addresses: 
      - address: "tCpERuK8HdBMFVShya49pgfBFVyxbzzgDp7EKKE2Nx6"
        amount: 2000000000
  poh:
    hashes_per_tick: 10
    ticks_per_slot: 4
    tick_interval_ms: 100
  mempool:
    max_txs: 100000
  validator:
    batch_size: 750
    leader_timeout: 50
    leader_timeout_loop_interval: 5