config:
  faucet:
    address: "faucet_address"
    amount: 1000000000000000000
  self_node:
    pubkey: "pubkey"
    privkey_path: "privkey_path"
    listen_addr: "listen_addr"
    libp2p_addr: "libp2p_addr"
    grpc_addr: "grpc_addr"
    bootstrap_addresses: 
      - "bootstrap_addresses"

  leader_schedule:
    - start_slot: start_slot
      end_slot: end_slot
      leader: "leader1"
    - start_slot: start_slot
      end_slot: end_slot
      leader: "leader2"
    - start_slot: start_slot
      end_slot: end_slot
      leader: "leader3"
