// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: blacklist.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlacklistService_Add_FullMethodName    = "/mmn.BlacklistService/Add"
	BlacklistService_List_FullMethodName   = "/mmn.BlacklistService/List"
	BlacklistService_Remove_FullMethodName = "/mmn.BlacklistService/Remove"
)

// BlacklistServiceClient is the client API for BlacklistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlacklistServiceClient interface {
	Add(ctx context.Context, in *SignedBL, opts ...grpc.CallOption) (*BlacklistResponse, error)
	List(ctx context.Context, in *SignedBL, opts ...grpc.CallOption) (*ListBlacklistResponse, error)
	Remove(ctx context.Context, in *SignedBL, opts ...grpc.CallOption) (*BlacklistResponse, error)
}

type blacklistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlacklistServiceClient(cc grpc.ClientConnInterface) BlacklistServiceClient {
	return &blacklistServiceClient{cc}
}

func (c *blacklistServiceClient) Add(ctx context.Context, in *SignedBL, opts ...grpc.CallOption) (*BlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlacklistResponse)
	err := c.cc.Invoke(ctx, BlacklistService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blacklistServiceClient) List(ctx context.Context, in *SignedBL, opts ...grpc.CallOption) (*ListBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlacklistResponse)
	err := c.cc.Invoke(ctx, BlacklistService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blacklistServiceClient) Remove(ctx context.Context, in *SignedBL, opts ...grpc.CallOption) (*BlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlacklistResponse)
	err := c.cc.Invoke(ctx, BlacklistService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlacklistServiceServer is the server API for BlacklistService service.
// All implementations must embed UnimplementedBlacklistServiceServer
// for forward compatibility.
type BlacklistServiceServer interface {
	Add(context.Context, *SignedBL) (*BlacklistResponse, error)
	List(context.Context, *SignedBL) (*ListBlacklistResponse, error)
	Remove(context.Context, *SignedBL) (*BlacklistResponse, error)
	mustEmbedUnimplementedBlacklistServiceServer()
}

// UnimplementedBlacklistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlacklistServiceServer struct{}

func (UnimplementedBlacklistServiceServer) Add(context.Context, *SignedBL) (*BlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedBlacklistServiceServer) List(context.Context, *SignedBL) (*ListBlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBlacklistServiceServer) Remove(context.Context, *SignedBL) (*BlacklistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedBlacklistServiceServer) mustEmbedUnimplementedBlacklistServiceServer() {}
func (UnimplementedBlacklistServiceServer) testEmbeddedByValue()                          {}

// UnsafeBlacklistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlacklistServiceServer will
// result in compilation errors.
type UnsafeBlacklistServiceServer interface {
	mustEmbedUnimplementedBlacklistServiceServer()
}

func RegisterBlacklistServiceServer(s grpc.ServiceRegistrar, srv BlacklistServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlacklistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlacklistService_ServiceDesc, srv)
}

func _BlacklistService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedBL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlacklistService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServiceServer).Add(ctx, req.(*SignedBL))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlacklistService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedBL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlacklistService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServiceServer).List(ctx, req.(*SignedBL))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlacklistService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedBL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlacklistService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServiceServer).Remove(ctx, req.(*SignedBL))
	}
	return interceptor(ctx, in, info, handler)
}

// BlacklistService_ServiceDesc is the grpc.ServiceDesc for BlacklistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlacklistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mmn.BlacklistService",
	HandlerType: (*BlacklistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _BlacklistService_Add_Handler,
		},
		{
			MethodName: "List",
			Handler:    _BlacklistService_List_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _BlacklistService_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blacklist.proto",
}
