// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: blacklist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignedBL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminAddress  string                 `protobuf:"bytes,1,opt,name=admin_address,json=adminAddress,proto3" json:"admin_address,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Sig           []byte                 `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBL) Reset() {
	*x = SignedBL{}
	mi := &file_blacklist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBL) ProtoMessage() {}

func (x *SignedBL) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBL.ProtoReflect.Descriptor instead.
func (*SignedBL) Descriptor() ([]byte, []int) {
	return file_blacklist_proto_rawDescGZIP(), []int{0}
}

func (x *SignedBL) GetAdminAddress() string {
	if x != nil {
		return x.AdminAddress
	}
	return ""
}

func (x *SignedBL) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SignedBL) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SignedBL) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type BlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistResponse) Reset() {
	*x = BlacklistResponse{}
	mi := &file_blacklist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistResponse) ProtoMessage() {}

func (x *BlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistResponse.ProtoReflect.Descriptor instead.
func (*BlacklistResponse) Descriptor() ([]byte, []int) {
	return file_blacklist_proto_rawDescGZIP(), []int{1}
}

func (x *BlacklistResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistRequest) Reset() {
	*x = ListBlacklistRequest{}
	mi := &file_blacklist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistRequest) ProtoMessage() {}

func (x *ListBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistRequest.ProtoReflect.Descriptor instead.
func (*ListBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_blacklist_proto_rawDescGZIP(), []int{2}
}

type ListBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]string      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // address -> reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistResponse) Reset() {
	*x = ListBlacklistResponse{}
	mi := &file_blacklist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistResponse) ProtoMessage() {}

func (x *ListBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blacklist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistResponse.ProtoReflect.Descriptor instead.
func (*ListBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_blacklist_proto_rawDescGZIP(), []int{3}
}

func (x *ListBlacklistResponse) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_blacklist_proto protoreflect.FileDescriptor

const file_blacklist_proto_rawDesc = "" +
	"\n" +
	"\x0fblacklist.proto\x12\x03mmn\"s\n" +
	"\bSignedBL\x12#\n" +
	"\radmin_address\x18\x01 \x01(\tR\fadminAddress\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x10\n" +
	"\x03sig\x18\x04 \x01(\fR\x03sig\"#\n" +
	"\x11BlacklistResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x16\n" +
	"\x14ListBlacklistRequest\"\x96\x01\n" +
	"\x15ListBlacklistResponse\x12A\n" +
	"\aentries\x18\x01 \x03(\v2'.mmn.ListBlacklistResponse.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa4\x01\n" +
	"\x10BlacklistService\x12,\n" +
	"\x03Add\x12\r.mmn.SignedBL\x1a\x16.mmn.BlacklistResponse\x121\n" +
	"\x04List\x12\r.mmn.SignedBL\x1a\x1a.mmn.ListBlacklistResponse\x12/\n" +
	"\x06Remove\x12\r.mmn.SignedBL\x1a\x16.mmn.BlacklistResponseB\x11Z\x0fmmn/proto;protob\x06proto3"

var (
	file_blacklist_proto_rawDescOnce sync.Once
	file_blacklist_proto_rawDescData []byte
)

func file_blacklist_proto_rawDescGZIP() []byte {
	file_blacklist_proto_rawDescOnce.Do(func() {
		file_blacklist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blacklist_proto_rawDesc), len(file_blacklist_proto_rawDesc)))
	})
	return file_blacklist_proto_rawDescData
}

var file_blacklist_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_blacklist_proto_goTypes = []any{
	(*SignedBL)(nil),              // 0: mmn.SignedBL
	(*BlacklistResponse)(nil),     // 1: mmn.BlacklistResponse
	(*ListBlacklistRequest)(nil),  // 2: mmn.ListBlacklistRequest
	(*ListBlacklistResponse)(nil), // 3: mmn.ListBlacklistResponse
	nil,                           // 4: mmn.ListBlacklistResponse.EntriesEntry
}
var file_blacklist_proto_depIdxs = []int32{
	4, // 0: mmn.ListBlacklistResponse.entries:type_name -> mmn.ListBlacklistResponse.EntriesEntry
	0, // 1: mmn.BlacklistService.Add:input_type -> mmn.SignedBL
	0, // 2: mmn.BlacklistService.List:input_type -> mmn.SignedBL
	0, // 3: mmn.BlacklistService.Remove:input_type -> mmn.SignedBL
	1, // 4: mmn.BlacklistService.Add:output_type -> mmn.BlacklistResponse
	3, // 5: mmn.BlacklistService.List:output_type -> mmn.ListBlacklistResponse
	1, // 6: mmn.BlacklistService.Remove:output_type -> mmn.BlacklistResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blacklist_proto_init() }
func file_blacklist_proto_init() {
	if File_blacklist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blacklist_proto_rawDesc), len(file_blacklist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blacklist_proto_goTypes,
		DependencyIndexes: file_blacklist_proto_depIdxs,
		MessageInfos:      file_blacklist_proto_msgTypes,
	}.Build()
	File_blacklist_proto = out.File
	file_blacklist_proto_goTypes = nil
	file_blacklist_proto_depIdxs = nil
}
