// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: tx.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction status enum
type TransactionStatus int32

const (
	TransactionStatus_PENDING   TransactionStatus = 0 // Transaction is in mempool
	TransactionStatus_CONFIRMED TransactionStatus = 1 // Transaction is included in a block
	TransactionStatus_FINALIZED TransactionStatus = 2 // Transaction is finalized (block has enough votes)
	TransactionStatus_FAILED    TransactionStatus = 3 // Transaction failed validation
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "PENDING",
		1: "CONFIRMED",
		2: "FINALIZED",
		3: "FAILED",
	}
	TransactionStatus_value = map[string]int32{
		"PENDING":   0,
		"CONFIRMED": 1,
		"FINALIZED": 2,
		"FAILED":    3,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[0]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

type TxMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TextData      string                 `protobuf:"bytes,6,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	Nonce         uint64                 `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxMsg) Reset() {
	*x = TxMsg{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxMsg) ProtoMessage() {}

func (x *TxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxMsg.ProtoReflect.Descriptor instead.
func (*TxMsg) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TxMsg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TxMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TxMsg) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *TxMsg) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TxMsg) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TxMsg) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

func (x *TxMsg) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type SignedTxMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxMsg         *TxMsg                 `protobuf:"bytes,1,opt,name=tx_msg,json=txMsg,proto3" json:"tx_msg,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTxMsg) Reset() {
	*x = SignedTxMsg{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTxMsg) ProtoMessage() {}

func (x *SignedTxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTxMsg.ProtoReflect.Descriptor instead.
func (*SignedTxMsg) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *SignedTxMsg) GetTxMsg() *TxMsg {
	if x != nil {
		return x.TxMsg
	}
	return nil
}

func (x *SignedTxMsg) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type TxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxResponse) Reset() {
	*x = TxResponse{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxResponse) ProtoMessage() {}

func (x *TxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxResponse.ProtoReflect.Descriptor instead.
func (*TxResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *TxResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTxResponse) Reset() {
	*x = AddTxResponse{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTxResponse) ProtoMessage() {}

func (x *AddTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTxResponse.ProtoReflect.Descriptor instead.
func (*AddTxResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *AddTxResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddTxResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AddTxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to get transaction status
type GetTransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionStatusRequest) Reset() {
	*x = GetTransactionStatusRequest{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionStatusRequest) ProtoMessage() {}

func (x *GetTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionStatusRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

// Unified transaction status message used for both unary and streaming responses
type TransactionStatusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=mmn.TransactionStatus" json:"status,omitempty"`
	BlockSlot     uint64                 `protobuf:"varint,3,opt,name=block_slot,json=blockSlot,proto3" json:"block_slot,omitempty"`         // Slot where transaction was included (if confirmed/finalized)
	BlockHash     string                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`          // Hash of the block (if confirmed/finalized)
	Confirmations uint64                 `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations,omitempty"`                  // Number of confirmations
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if failed
	Timestamp     uint64                 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // Timestamp when status was last updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatusInfo) Reset() {
	*x = TransactionStatusInfo{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusInfo) ProtoMessage() {}

func (x *TransactionStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusInfo.ProtoReflect.Descriptor instead.
func (*TransactionStatusInfo) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionStatusInfo) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionStatusInfo) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_PENDING
}

func (x *TransactionStatusInfo) GetBlockSlot() uint64 {
	if x != nil {
		return x.BlockSlot
	}
	return 0
}

func (x *TransactionStatusInfo) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *TransactionStatusInfo) GetConfirmations() uint64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *TransactionStatusInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TransactionStatusInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Request to subscribe to all transaction status updates
type SubscribeTransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTransactionStatusRequest) Reset() {
	*x = SubscribeTransactionStatusRequest{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTransactionStatusRequest) ProtoMessage() {}

func (x *SubscribeTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x03mmn\"\xba\x01\n" +
	"\x05TxMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\ttext_data\x18\x06 \x01(\tR\btextData\x12\x14\n" +
	"\x05nonce\x18\a \x01(\x04R\x05nonce\"N\n" +
	"\vSignedTxMsg\x12!\n" +
	"\x06tx_msg\x18\x01 \x01(\v2\n" +
	".mmn.TxMsgR\x05txMsg\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"2\n" +
	"\n" +
	"TxResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"N\n" +
	"\rAddTxResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"6\n" +
	"\x1bGetTransactionStatusRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"\x87\x02\n" +
	"\x15TransactionStatusInfo\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.mmn.TransactionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"block_slot\x18\x03 \x01(\x04R\tblockSlot\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\tR\tblockHash\x12$\n" +
	"\rconfirmations\x18\x05 \x01(\x04R\rconfirmations\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestamp\"#\n" +
	"!SubscribeTransactionStatusRequest*J\n" +
	"\x11TransactionStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\r\n" +
	"\tFINALIZED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\xa6\x02\n" +
	"\tTxService\x120\n" +
	"\vTxBroadcast\x12\x10.mmn.SignedTxMsg\x1a\x0f.mmn.TxResponse\x12-\n" +
	"\x05AddTx\x12\x10.mmn.SignedTxMsg\x1a\x12.mmn.AddTxResponse\x12T\n" +
	"\x14GetTransactionStatus\x12 .mmn.GetTransactionStatusRequest\x1a\x1a.mmn.TransactionStatusInfo\x12b\n" +
	"\x1aSubscribeTransactionStatus\x12&.mmn.SubscribeTransactionStatusRequest\x1a\x1a.mmn.TransactionStatusInfo0\x01B\x11Z\x0fmmn/proto;protob\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tx_proto_goTypes = []any{
	(TransactionStatus)(0),                    // 0: mmn.TransactionStatus
	(*TxMsg)(nil),                             // 1: mmn.TxMsg
	(*SignedTxMsg)(nil),                       // 2: mmn.SignedTxMsg
	(*TxResponse)(nil),                        // 3: mmn.TxResponse
	(*AddTxResponse)(nil),                     // 4: mmn.AddTxResponse
	(*GetTransactionStatusRequest)(nil),       // 5: mmn.GetTransactionStatusRequest
	(*TransactionStatusInfo)(nil),             // 6: mmn.TransactionStatusInfo
	(*SubscribeTransactionStatusRequest)(nil), // 7: mmn.SubscribeTransactionStatusRequest
}
var file_tx_proto_depIdxs = []int32{
	1, // 0: mmn.SignedTxMsg.tx_msg:type_name -> mmn.TxMsg
	0, // 1: mmn.TransactionStatusInfo.status:type_name -> mmn.TransactionStatus
	2, // 2: mmn.TxService.TxBroadcast:input_type -> mmn.SignedTxMsg
	2, // 3: mmn.TxService.AddTx:input_type -> mmn.SignedTxMsg
	5, // 4: mmn.TxService.GetTransactionStatus:input_type -> mmn.GetTransactionStatusRequest
	7, // 5: mmn.TxService.SubscribeTransactionStatus:input_type -> mmn.SubscribeTransactionStatusRequest
	3, // 6: mmn.TxService.TxBroadcast:output_type -> mmn.TxResponse
	4, // 7: mmn.TxService.AddTx:output_type -> mmn.AddTxResponse
	6, // 8: mmn.TxService.GetTransactionStatus:output_type -> mmn.TransactionStatusInfo
	6, // 9: mmn.TxService.SubscribeTransactionStatus:output_type -> mmn.TransactionStatusInfo
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		EnumInfos:         file_tx_proto_enumTypes,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
