// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tx.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction status enum
type TransactionStatus int32

const (
	TransactionStatus_PENDING   TransactionStatus = 0 // Transaction is in mempool
	TransactionStatus_CONFIRMED TransactionStatus = 1 // Transaction is included in a block
	TransactionStatus_FINALIZED TransactionStatus = 2 // Transaction is finalized (block has enough votes)
	TransactionStatus_FAILED    TransactionStatus = 3 // Transaction failed validation
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "PENDING",
		1: "CONFIRMED",
		2: "FINALIZED",
		3: "FAILED",
	}
	TransactionStatus_value = map[string]int32{
		"PENDING":   0,
		"CONFIRMED": 1,
		"FINALIZED": 2,
		"FAILED":    3,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[0]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

// Transaction data structure for transactions
type TransactionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`       // sender address
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"` // recipient address
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`       // amount
	Nonce         uint64                 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`        // nonce
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,7,opt,name=status,proto3,enum=mmn.TransactionStatus" json:"status,omitempty"`
	TextData      string                 `protobuf:"bytes,8,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,9,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionData) Reset() {
	*x = TransactionData{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionData) ProtoMessage() {}

func (x *TransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionData.ProtoReflect.Descriptor instead.
func (*TransactionData) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionData) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionData) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TransactionData) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *TransactionData) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransactionData) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TransactionData) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionData) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_PENDING
}

func (x *TransactionData) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

func (x *TransactionData) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

type TxMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TextData      string                 `protobuf:"bytes,6,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	Nonce         uint64                 `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,8,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	ZkProof       string                 `protobuf:"bytes,9,opt,name=zk_proof,json=zkProof,proto3" json:"zk_proof,omitempty"`
	ZkPub         string                 `protobuf:"bytes,10,opt,name=zk_pub,json=zkPub,proto3" json:"zk_pub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxMsg) Reset() {
	*x = TxMsg{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxMsg) ProtoMessage() {}

func (x *TxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxMsg.ProtoReflect.Descriptor instead.
func (*TxMsg) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TxMsg) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TxMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TxMsg) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *TxMsg) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TxMsg) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TxMsg) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

func (x *TxMsg) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TxMsg) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

func (x *TxMsg) GetZkProof() string {
	if x != nil {
		return x.ZkProof
	}
	return ""
}

func (x *TxMsg) GetZkPub() string {
	if x != nil {
		return x.ZkPub
	}
	return ""
}

type SignedTxMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxMsg         *TxMsg                 `protobuf:"bytes,1,opt,name=tx_msg,json=txMsg,proto3" json:"tx_msg,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTxMsg) Reset() {
	*x = SignedTxMsg{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTxMsg) ProtoMessage() {}

func (x *SignedTxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTxMsg.ProtoReflect.Descriptor instead.
func (*SignedTxMsg) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *SignedTxMsg) GetTxMsg() *TxMsg {
	if x != nil {
		return x.TxMsg
	}
	return nil
}

func (x *SignedTxMsg) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AddTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTxResponse) Reset() {
	*x = AddTxResponse{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTxResponse) ProtoMessage() {}

func (x *AddTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTxResponse.ProtoReflect.Descriptor instead.
func (*AddTxResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *AddTxResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddTxResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AddTxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTxByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxByHashRequest) Reset() {
	*x = GetTxByHashRequest{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxByHashRequest) ProtoMessage() {}

func (x *GetTxByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxByHashRequest.ProtoReflect.Descriptor instead.
func (*GetTxByHashRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *GetTxByHashRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type TxInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TextData      string                 `protobuf:"bytes,5,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	Nonce         uint64                 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Slot          uint64                 `protobuf:"varint,7,opt,name=slot,proto3" json:"slot,omitempty"`
	Blockhash     string                 `protobuf:"bytes,8,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,10,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,11,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxInfo) Reset() {
	*x = TxInfo{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInfo) ProtoMessage() {}

func (x *TxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInfo.ProtoReflect.Descriptor instead.
func (*TxInfo) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *TxInfo) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TxInfo) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *TxInfo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TxInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TxInfo) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

func (x *TxInfo) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TxInfo) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *TxInfo) GetBlockhash() string {
	if x != nil {
		return x.Blockhash
	}
	return ""
}

func (x *TxInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TxInfo) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *TxInfo) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

type GetTxByHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Tx            *TxInfo                `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	Decimals      uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"` // Number of fractional digits for amount formatting
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxByHashResponse) Reset() {
	*x = GetTxByHashResponse{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxByHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxByHashResponse) ProtoMessage() {}

func (x *GetTxByHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxByHashResponse.ProtoReflect.Descriptor instead.
func (*GetTxByHashResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *GetTxByHashResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTxByHashResponse) GetTx() *TxInfo {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *GetTxByHashResponse) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

// Request to get transaction status
type GetTransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionStatusRequest) Reset() {
	*x = GetTransactionStatusRequest{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionStatusRequest) ProtoMessage() {}

func (x *GetTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionStatusRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

// Unified transaction status message used for both unary and streaming responses
// TODO: consider to have single field as wrapper for all original transaction attributes (amount, text data, extra...) to avoid code duplication
type TransactionStatusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=mmn.TransactionStatus" json:"status,omitempty"`
	BlockSlot     uint64                 `protobuf:"varint,3,opt,name=block_slot,json=blockSlot,proto3" json:"block_slot,omitempty"`         // Slot where transaction was included (if confirmed/finalized)
	BlockHash     string                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`          // Hash of the block (if confirmed/finalized)
	Confirmations uint64                 `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations,omitempty"`                  // Number of confirmations
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if failed
	Timestamp     uint64                 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // Timestamp when status was last updated
	ExtraInfo     string                 `protobuf:"bytes,8,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`          // Extra info that was attached to transaction on creation
	Amount        string                 `protobuf:"bytes,9,opt,name=amount,proto3" json:"amount,omitempty"`                                 // Transaction amount
	TextData      string                 `protobuf:"bytes,10,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`            // Transaction text data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatusInfo) Reset() {
	*x = TransactionStatusInfo{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusInfo) ProtoMessage() {}

func (x *TransactionStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusInfo.ProtoReflect.Descriptor instead.
func (*TransactionStatusInfo) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionStatusInfo) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionStatusInfo) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_PENDING
}

func (x *TransactionStatusInfo) GetBlockSlot() uint64 {
	if x != nil {
		return x.BlockSlot
	}
	return 0
}

func (x *TransactionStatusInfo) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *TransactionStatusInfo) GetConfirmations() uint64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *TransactionStatusInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TransactionStatusInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionStatusInfo) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

func (x *TransactionStatusInfo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransactionStatusInfo) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

// Request to subscribe to all transaction status updates
type SubscribeTransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTransactionStatusRequest) Reset() {
	*x = SubscribeTransactionStatusRequest{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTransactionStatusRequest) ProtoMessage() {}

func (x *SubscribeTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

// Request to get all pending transactions
type GetPendingTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTransactionsRequest) Reset() {
	*x = GetPendingTransactionsRequest{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTransactionsRequest) ProtoMessage() {}

func (x *GetPendingTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

// Response containing pending transactions information
type GetPendingTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    uint64                 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	PendingTxs    []*TransactionData     `protobuf:"bytes,2,rep,name=pending_txs,json=pendingTxs,proto3" json:"pending_txs,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTransactionsResponse) Reset() {
	*x = GetPendingTransactionsResponse{}
	mi := &file_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTransactionsResponse) ProtoMessage() {}

func (x *GetPendingTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11}
}

func (x *GetPendingTransactionsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetPendingTransactionsResponse) GetPendingTxs() []*TransactionData {
	if x != nil {
		return x.PendingTxs
	}
	return nil
}

func (x *GetPendingTransactionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Create Faucet Request
type CreateFaucetRequestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MultisigAddress string                 `protobuf:"bytes,1,opt,name=multisig_address,json=multisigAddress,proto3" json:"multisig_address,omitempty"`
	Recipient       string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount          string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TextData        string                 `protobuf:"bytes,4,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	SignerPubkey    string                 `protobuf:"bytes,5,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"`
	Signature       string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // Hex encoded signature
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateFaucetRequestRequest) Reset() {
	*x = CreateFaucetRequestRequest{}
	mi := &file_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFaucetRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFaucetRequestRequest) ProtoMessage() {}

func (x *CreateFaucetRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFaucetRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateFaucetRequestRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{12}
}

func (x *CreateFaucetRequestRequest) GetMultisigAddress() string {
	if x != nil {
		return x.MultisigAddress
	}
	return ""
}

func (x *CreateFaucetRequestRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateFaucetRequestRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateFaucetRequestRequest) GetTextData() string {
	if x != nil {
		return x.TextData
	}
	return ""
}

func (x *CreateFaucetRequestRequest) GetSignerPubkey() string {
	if x != nil {
		return x.SignerPubkey
	}
	return ""
}

func (x *CreateFaucetRequestRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type CreateFaucetRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFaucetRequestResponse) Reset() {
	*x = CreateFaucetRequestResponse{}
	mi := &file_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFaucetRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFaucetRequestResponse) ProtoMessage() {}

func (x *CreateFaucetRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFaucetRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateFaucetRequestResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{13}
}

func (x *CreateFaucetRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateFaucetRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateFaucetRequestResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

// Add Signature
type AddSignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	SignerPubkey  string                 `protobuf:"bytes,2,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Hex encoded signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSignatureRequest) Reset() {
	*x = AddSignatureRequest{}
	mi := &file_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSignatureRequest) ProtoMessage() {}

func (x *AddSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSignatureRequest.ProtoReflect.Descriptor instead.
func (*AddSignatureRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{14}
}

func (x *AddSignatureRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AddSignatureRequest) GetSignerPubkey() string {
	if x != nil {
		return x.SignerPubkey
	}
	return ""
}

func (x *AddSignatureRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AddSignatureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SignatureCount int32                  `protobuf:"varint,3,opt,name=signature_count,json=signatureCount,proto3" json:"signature_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddSignatureResponse) Reset() {
	*x = AddSignatureResponse{}
	mi := &file_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSignatureResponse) ProtoMessage() {}

func (x *AddSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSignatureResponse.ProtoReflect.Descriptor instead.
func (*AddSignatureResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{15}
}

func (x *AddSignatureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddSignatureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddSignatureResponse) GetSignatureCount() int32 {
	if x != nil {
		return x.SignatureCount
	}
	return 0
}

// Get Multisig Transaction Status
type GetMultisigTransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultisigTransactionStatusRequest) Reset() {
	*x = GetMultisigTransactionStatusRequest{}
	mi := &file_tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultisigTransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultisigTransactionStatusRequest) ProtoMessage() {}

func (x *GetMultisigTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultisigTransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMultisigTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{16}
}

func (x *GetMultisigTransactionStatusRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type GetMultisigTransactionStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // pending, executed, failed
	SignatureCount     int32                  `protobuf:"varint,4,opt,name=signature_count,json=signatureCount,proto3" json:"signature_count,omitempty"`
	RequiredSignatures int32                  `protobuf:"varint,5,opt,name=required_signatures,json=requiredSignatures,proto3" json:"required_signatures,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetMultisigTransactionStatusResponse) Reset() {
	*x = GetMultisigTransactionStatusResponse{}
	mi := &file_tx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultisigTransactionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultisigTransactionStatusResponse) ProtoMessage() {}

func (x *GetMultisigTransactionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultisigTransactionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMultisigTransactionStatusResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{17}
}

func (x *GetMultisigTransactionStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMultisigTransactionStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMultisigTransactionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMultisigTransactionStatusResponse) GetSignatureCount() int32 {
	if x != nil {
		return x.SignatureCount
	}
	return 0
}

func (x *GetMultisigTransactionStatusResponse) GetRequiredSignatures() int32 {
	if x != nil {
		return x.RequiredSignatures
	}
	return 0
}

// Whitelist Management
type AddToApproverWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	SignerPubkey  string                 `protobuf:"bytes,2,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Hex encoded signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToApproverWhitelistRequest) Reset() {
	*x = AddToApproverWhitelistRequest{}
	mi := &file_tx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToApproverWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToApproverWhitelistRequest) ProtoMessage() {}

func (x *AddToApproverWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToApproverWhitelistRequest.ProtoReflect.Descriptor instead.
func (*AddToApproverWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{18}
}

func (x *AddToApproverWhitelistRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddToApproverWhitelistRequest) GetSignerPubkey() string {
	if x != nil {
		return x.SignerPubkey
	}
	return ""
}

func (x *AddToApproverWhitelistRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AddToApproverWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToApproverWhitelistResponse) Reset() {
	*x = AddToApproverWhitelistResponse{}
	mi := &file_tx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToApproverWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToApproverWhitelistResponse) ProtoMessage() {}

func (x *AddToApproverWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToApproverWhitelistResponse.ProtoReflect.Descriptor instead.
func (*AddToApproverWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{19}
}

func (x *AddToApproverWhitelistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddToApproverWhitelistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddToProposerWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	SignerPubkey  string                 `protobuf:"bytes,2,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Hex encoded signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToProposerWhitelistRequest) Reset() {
	*x = AddToProposerWhitelistRequest{}
	mi := &file_tx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToProposerWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToProposerWhitelistRequest) ProtoMessage() {}

func (x *AddToProposerWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToProposerWhitelistRequest.ProtoReflect.Descriptor instead.
func (*AddToProposerWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{20}
}

func (x *AddToProposerWhitelistRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddToProposerWhitelistRequest) GetSignerPubkey() string {
	if x != nil {
		return x.SignerPubkey
	}
	return ""
}

func (x *AddToProposerWhitelistRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AddToProposerWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToProposerWhitelistResponse) Reset() {
	*x = AddToProposerWhitelistResponse{}
	mi := &file_tx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToProposerWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToProposerWhitelistResponse) ProtoMessage() {}

func (x *AddToProposerWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToProposerWhitelistResponse.ProtoReflect.Descriptor instead.
func (*AddToProposerWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{21}
}

func (x *AddToProposerWhitelistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddToProposerWhitelistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveFromApproverWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	SignerPubkey  string                 `protobuf:"bytes,2,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Hex encoded signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromApproverWhitelistRequest) Reset() {
	*x = RemoveFromApproverWhitelistRequest{}
	mi := &file_tx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromApproverWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromApproverWhitelistRequest) ProtoMessage() {}

func (x *RemoveFromApproverWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromApproverWhitelistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromApproverWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveFromApproverWhitelistRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RemoveFromApproverWhitelistRequest) GetSignerPubkey() string {
	if x != nil {
		return x.SignerPubkey
	}
	return ""
}

func (x *RemoveFromApproverWhitelistRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type RemoveFromApproverWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromApproverWhitelistResponse) Reset() {
	*x = RemoveFromApproverWhitelistResponse{}
	mi := &file_tx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromApproverWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromApproverWhitelistResponse) ProtoMessage() {}

func (x *RemoveFromApproverWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromApproverWhitelistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromApproverWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveFromApproverWhitelistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveFromApproverWhitelistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveFromProposerWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	SignerPubkey  string                 `protobuf:"bytes,2,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Hex encoded signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromProposerWhitelistRequest) Reset() {
	*x = RemoveFromProposerWhitelistRequest{}
	mi := &file_tx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromProposerWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromProposerWhitelistRequest) ProtoMessage() {}

func (x *RemoveFromProposerWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromProposerWhitelistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromProposerWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveFromProposerWhitelistRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RemoveFromProposerWhitelistRequest) GetSignerPubkey() string {
	if x != nil {
		return x.SignerPubkey
	}
	return ""
}

func (x *RemoveFromProposerWhitelistRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type RemoveFromProposerWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromProposerWhitelistResponse) Reset() {
	*x = RemoveFromProposerWhitelistResponse{}
	mi := &file_tx_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromProposerWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromProposerWhitelistResponse) ProtoMessage() {}

func (x *RemoveFromProposerWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromProposerWhitelistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromProposerWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveFromProposerWhitelistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveFromProposerWhitelistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Check Whitelist Status
type CheckWhitelistStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckWhitelistStatusRequest) Reset() {
	*x = CheckWhitelistStatusRequest{}
	mi := &file_tx_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWhitelistStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWhitelistStatusRequest) ProtoMessage() {}

func (x *CheckWhitelistStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWhitelistStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckWhitelistStatusRequest) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{26}
}

func (x *CheckWhitelistStatusRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CheckWhitelistStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsApprover    bool                   `protobuf:"varint,3,opt,name=is_approver,json=isApprover,proto3" json:"is_approver,omitempty"`
	IsProposer    bool                   `protobuf:"varint,4,opt,name=is_proposer,json=isProposer,proto3" json:"is_proposer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckWhitelistStatusResponse) Reset() {
	*x = CheckWhitelistStatusResponse{}
	mi := &file_tx_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWhitelistStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWhitelistStatusResponse) ProtoMessage() {}

func (x *CheckWhitelistStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWhitelistStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckWhitelistStatusResponse) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{27}
}

func (x *CheckWhitelistStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckWhitelistStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckWhitelistStatusResponse) GetIsApprover() bool {
	if x != nil {
		return x.IsApprover
	}
	return false
}

func (x *CheckWhitelistStatusResponse) GetIsProposer() bool {
	if x != nil {
		return x.IsProposer
	}
	return false
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x03mmn\"\x98\x02\n" +
	"\x0fTransactionData\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12.\n" +
	"\x06status\x18\a \x01(\x0e2\x16.mmn.TransactionStatusR\x06status\x12\x1b\n" +
	"\ttext_data\x18\b \x01(\tR\btextData\x12\x1d\n" +
	"\n" +
	"extra_info\x18\t \x01(\tR\textraInfo\"\x8b\x02\n" +
	"\x05TxMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\ttext_data\x18\x06 \x01(\tR\btextData\x12\x14\n" +
	"\x05nonce\x18\a \x01(\x04R\x05nonce\x12\x1d\n" +
	"\n" +
	"extra_info\x18\b \x01(\tR\textraInfo\x12\x19\n" +
	"\bzk_proof\x18\t \x01(\tR\azkProof\x12\x15\n" +
	"\x06zk_pub\x18\n" +
	" \x01(\tR\x05zkPub\"N\n" +
	"\vSignedTxMsg\x12!\n" +
	"\x06tx_msg\x18\x01 \x01(\v2\n" +
	".mmn.TxMsgR\x05txMsg\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"N\n" +
	"\rAddTxResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"-\n" +
	"\x12GetTxByHashRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"\xa9\x02\n" +
	"\x06TxInfo\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\ttext_data\x18\x05 \x01(\tR\btextData\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12\x12\n" +
	"\x04slot\x18\a \x01(\x04R\x04slot\x12\x1c\n" +
	"\tblockhash\x18\b \x01(\tR\tblockhash\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x17\n" +
	"\aerr_msg\x18\n" +
	" \x01(\tR\x06errMsg\x12\x1d\n" +
	"\n" +
	"extra_info\x18\v \x01(\tR\textraInfo\"d\n" +
	"\x13GetTxByHashResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1b\n" +
	"\x02tx\x18\x02 \x01(\v2\v.mmn.TxInfoR\x02tx\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\"6\n" +
	"\x1bGetTransactionStatusRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"\xdb\x02\n" +
	"\x15TransactionStatusInfo\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.mmn.TransactionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"block_slot\x18\x03 \x01(\x04R\tblockSlot\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\tR\tblockHash\x12$\n" +
	"\rconfirmations\x18\x05 \x01(\x04R\rconfirmations\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"extra_info\x18\b \x01(\tR\textraInfo\x12\x16\n" +
	"\x06amount\x18\t \x01(\tR\x06amount\x12\x1b\n" +
	"\ttext_data\x18\n" +
	" \x01(\tR\btextData\"#\n" +
	"!SubscribeTransactionStatusRequest\"\x1f\n" +
	"\x1dGetPendingTransactionsRequest\"\x8e\x01\n" +
	"\x1eGetPendingTransactionsResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x04R\n" +
	"totalCount\x125\n" +
	"\vpending_txs\x18\x02 \x03(\v2\x14.mmn.TransactionDataR\n" +
	"pendingTxs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xdd\x01\n" +
	"\x1aCreateFaucetRequestRequest\x12)\n" +
	"\x10multisig_address\x18\x01 \x01(\tR\x0fmultisigAddress\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x1b\n" +
	"\ttext_data\x18\x04 \x01(\tR\btextData\x12#\n" +
	"\rsigner_pubkey\x18\x05 \x01(\tR\fsignerPubkey\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\"j\n" +
	"\x1bCreateFaucetRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\"q\n" +
	"\x13AddSignatureRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12#\n" +
	"\rsigner_pubkey\x18\x02 \x01(\tR\fsignerPubkey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"s\n" +
	"\x14AddSignatureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fsignature_count\x18\x03 \x01(\x05R\x0esignatureCount\">\n" +
	"#GetMultisigTransactionStatusRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"\xcc\x01\n" +
	"$GetMultisigTransactionStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fsignature_count\x18\x04 \x01(\x05R\x0esignatureCount\x12/\n" +
	"\x13required_signatures\x18\x05 \x01(\x05R\x12requiredSignatures\"|\n" +
	"\x1dAddToApproverWhitelistRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12#\n" +
	"\rsigner_pubkey\x18\x02 \x01(\tR\fsignerPubkey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"T\n" +
	"\x1eAddToApproverWhitelistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"|\n" +
	"\x1dAddToProposerWhitelistRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12#\n" +
	"\rsigner_pubkey\x18\x02 \x01(\tR\fsignerPubkey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"T\n" +
	"\x1eAddToProposerWhitelistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x01\n" +
	"\"RemoveFromApproverWhitelistRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12#\n" +
	"\rsigner_pubkey\x18\x02 \x01(\tR\fsignerPubkey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"Y\n" +
	"#RemoveFromApproverWhitelistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x01\n" +
	"\"RemoveFromProposerWhitelistRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12#\n" +
	"\rsigner_pubkey\x18\x02 \x01(\tR\fsignerPubkey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"Y\n" +
	"#RemoveFromProposerWhitelistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x1bCheckWhitelistStatusRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x94\x01\n" +
	"\x1cCheckWhitelistStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vis_approver\x18\x03 \x01(\bR\n" +
	"isApprover\x12\x1f\n" +
	"\vis_proposer\x18\x04 \x01(\bR\n" +
	"isProposer*J\n" +
	"\x11TransactionStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\r\n" +
	"\tFINALIZED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\xb4\t\n" +
	"\tTxService\x12-\n" +
	"\x05AddTx\x12\x10.mmn.SignedTxMsg\x1a\x12.mmn.AddTxResponse\x12@\n" +
	"\vGetTxByHash\x12\x17.mmn.GetTxByHashRequest\x1a\x18.mmn.GetTxByHashResponse\x12T\n" +
	"\x14GetTransactionStatus\x12 .mmn.GetTransactionStatusRequest\x1a\x1a.mmn.TransactionStatusInfo\x12b\n" +
	"\x1aSubscribeTransactionStatus\x12&.mmn.SubscribeTransactionStatusRequest\x1a\x1a.mmn.TransactionStatusInfo0\x01\x12a\n" +
	"\x16GetPendingTransactions\x12\".mmn.GetPendingTransactionsRequest\x1a#.mmn.GetPendingTransactionsResponse\x12X\n" +
	"\x13CreateFaucetRequest\x12\x1f.mmn.CreateFaucetRequestRequest\x1a .mmn.CreateFaucetRequestResponse\x12C\n" +
	"\fAddSignature\x12\x18.mmn.AddSignatureRequest\x1a\x19.mmn.AddSignatureResponse\x12s\n" +
	"\x1cGetMultisigTransactionStatus\x12(.mmn.GetMultisigTransactionStatusRequest\x1a).mmn.GetMultisigTransactionStatusResponse\x12a\n" +
	"\x16AddToApproverWhitelist\x12\".mmn.AddToApproverWhitelistRequest\x1a#.mmn.AddToApproverWhitelistResponse\x12a\n" +
	"\x16AddToProposerWhitelist\x12\".mmn.AddToProposerWhitelistRequest\x1a#.mmn.AddToProposerWhitelistResponse\x12p\n" +
	"\x1bRemoveFromApproverWhitelist\x12'.mmn.RemoveFromApproverWhitelistRequest\x1a(.mmn.RemoveFromApproverWhitelistResponse\x12p\n" +
	"\x1bRemoveFromProposerWhitelist\x12'.mmn.RemoveFromProposerWhitelistRequest\x1a(.mmn.RemoveFromProposerWhitelistResponse\x12[\n" +
	"\x14CheckWhitelistStatus\x12 .mmn.CheckWhitelistStatusRequest\x1a!.mmn.CheckWhitelistStatusResponseB\x11Z\x0fmmn/proto;protob\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_tx_proto_goTypes = []any{
	(TransactionStatus)(0),                       // 0: mmn.TransactionStatus
	(*TransactionData)(nil),                      // 1: mmn.TransactionData
	(*TxMsg)(nil),                                // 2: mmn.TxMsg
	(*SignedTxMsg)(nil),                          // 3: mmn.SignedTxMsg
	(*AddTxResponse)(nil),                        // 4: mmn.AddTxResponse
	(*GetTxByHashRequest)(nil),                   // 5: mmn.GetTxByHashRequest
	(*TxInfo)(nil),                               // 6: mmn.TxInfo
	(*GetTxByHashResponse)(nil),                  // 7: mmn.GetTxByHashResponse
	(*GetTransactionStatusRequest)(nil),          // 8: mmn.GetTransactionStatusRequest
	(*TransactionStatusInfo)(nil),                // 9: mmn.TransactionStatusInfo
	(*SubscribeTransactionStatusRequest)(nil),    // 10: mmn.SubscribeTransactionStatusRequest
	(*GetPendingTransactionsRequest)(nil),        // 11: mmn.GetPendingTransactionsRequest
	(*GetPendingTransactionsResponse)(nil),       // 12: mmn.GetPendingTransactionsResponse
	(*CreateFaucetRequestRequest)(nil),           // 13: mmn.CreateFaucetRequestRequest
	(*CreateFaucetRequestResponse)(nil),          // 14: mmn.CreateFaucetRequestResponse
	(*AddSignatureRequest)(nil),                  // 15: mmn.AddSignatureRequest
	(*AddSignatureResponse)(nil),                 // 16: mmn.AddSignatureResponse
	(*GetMultisigTransactionStatusRequest)(nil),  // 17: mmn.GetMultisigTransactionStatusRequest
	(*GetMultisigTransactionStatusResponse)(nil), // 18: mmn.GetMultisigTransactionStatusResponse
	(*AddToApproverWhitelistRequest)(nil),        // 19: mmn.AddToApproverWhitelistRequest
	(*AddToApproverWhitelistResponse)(nil),       // 20: mmn.AddToApproverWhitelistResponse
	(*AddToProposerWhitelistRequest)(nil),        // 21: mmn.AddToProposerWhitelistRequest
	(*AddToProposerWhitelistResponse)(nil),       // 22: mmn.AddToProposerWhitelistResponse
	(*RemoveFromApproverWhitelistRequest)(nil),   // 23: mmn.RemoveFromApproverWhitelistRequest
	(*RemoveFromApproverWhitelistResponse)(nil),  // 24: mmn.RemoveFromApproverWhitelistResponse
	(*RemoveFromProposerWhitelistRequest)(nil),   // 25: mmn.RemoveFromProposerWhitelistRequest
	(*RemoveFromProposerWhitelistResponse)(nil),  // 26: mmn.RemoveFromProposerWhitelistResponse
	(*CheckWhitelistStatusRequest)(nil),          // 27: mmn.CheckWhitelistStatusRequest
	(*CheckWhitelistStatusResponse)(nil),         // 28: mmn.CheckWhitelistStatusResponse
}
var file_tx_proto_depIdxs = []int32{
	0,  // 0: mmn.TransactionData.status:type_name -> mmn.TransactionStatus
	2,  // 1: mmn.SignedTxMsg.tx_msg:type_name -> mmn.TxMsg
	6,  // 2: mmn.GetTxByHashResponse.tx:type_name -> mmn.TxInfo
	0,  // 3: mmn.TransactionStatusInfo.status:type_name -> mmn.TransactionStatus
	1,  // 4: mmn.GetPendingTransactionsResponse.pending_txs:type_name -> mmn.TransactionData
	3,  // 5: mmn.TxService.AddTx:input_type -> mmn.SignedTxMsg
	5,  // 6: mmn.TxService.GetTxByHash:input_type -> mmn.GetTxByHashRequest
	8,  // 7: mmn.TxService.GetTransactionStatus:input_type -> mmn.GetTransactionStatusRequest
	10, // 8: mmn.TxService.SubscribeTransactionStatus:input_type -> mmn.SubscribeTransactionStatusRequest
	11, // 9: mmn.TxService.GetPendingTransactions:input_type -> mmn.GetPendingTransactionsRequest
	13, // 10: mmn.TxService.CreateFaucetRequest:input_type -> mmn.CreateFaucetRequestRequest
	15, // 11: mmn.TxService.AddSignature:input_type -> mmn.AddSignatureRequest
	17, // 12: mmn.TxService.GetMultisigTransactionStatus:input_type -> mmn.GetMultisigTransactionStatusRequest
	19, // 13: mmn.TxService.AddToApproverWhitelist:input_type -> mmn.AddToApproverWhitelistRequest
	21, // 14: mmn.TxService.AddToProposerWhitelist:input_type -> mmn.AddToProposerWhitelistRequest
	23, // 15: mmn.TxService.RemoveFromApproverWhitelist:input_type -> mmn.RemoveFromApproverWhitelistRequest
	25, // 16: mmn.TxService.RemoveFromProposerWhitelist:input_type -> mmn.RemoveFromProposerWhitelistRequest
	27, // 17: mmn.TxService.CheckWhitelistStatus:input_type -> mmn.CheckWhitelistStatusRequest
	4,  // 18: mmn.TxService.AddTx:output_type -> mmn.AddTxResponse
	7,  // 19: mmn.TxService.GetTxByHash:output_type -> mmn.GetTxByHashResponse
	9,  // 20: mmn.TxService.GetTransactionStatus:output_type -> mmn.TransactionStatusInfo
	9,  // 21: mmn.TxService.SubscribeTransactionStatus:output_type -> mmn.TransactionStatusInfo
	12, // 22: mmn.TxService.GetPendingTransactions:output_type -> mmn.GetPendingTransactionsResponse
	14, // 23: mmn.TxService.CreateFaucetRequest:output_type -> mmn.CreateFaucetRequestResponse
	16, // 24: mmn.TxService.AddSignature:output_type -> mmn.AddSignatureResponse
	18, // 25: mmn.TxService.GetMultisigTransactionStatus:output_type -> mmn.GetMultisigTransactionStatusResponse
	20, // 26: mmn.TxService.AddToApproverWhitelist:output_type -> mmn.AddToApproverWhitelistResponse
	22, // 27: mmn.TxService.AddToProposerWhitelist:output_type -> mmn.AddToProposerWhitelistResponse
	24, // 28: mmn.TxService.RemoveFromApproverWhitelist:output_type -> mmn.RemoveFromApproverWhitelistResponse
	26, // 29: mmn.TxService.RemoveFromProposerWhitelist:output_type -> mmn.RemoveFromProposerWhitelistResponse
	28, // 30: mmn.TxService.CheckWhitelistStatus:output_type -> mmn.CheckWhitelistStatusResponse
	18, // [18:31] is the sub-list for method output_type
	5,  // [5:18] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		EnumInfos:         file_tx_proto_enumTypes,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
