{
 "title": "MMN Node",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node State",
   "type": "stat",
   "description": "Node running state",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{node=\"$node\",job=\"node\"}",
     "legendFormat": "Node State"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Node uptime",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - mmn_node_up_timestamp_unix_seconds{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "description": "Node block height",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmn_node_block_height{node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "description": "Number of peer connections",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mmn_node_peer_count{node=\"$node\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "System CPU usage",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg (rate(node_cpu_seconds_total{mode=\"idle\", node=\"$node\"}[$__rate_interval]))) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "System memory usage",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{node=\"$node\"}) / node_memory_MemTotal_bytes{node=\"$node\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "System disk usage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - (sum (node_filesystem_avail_bytes{node=\"$node\",fstype!=\"tmpfs\",fstype!=\"overlay\"}) / sum (node_filesystem_size_bytes{node=\"$node\",fstype!=\"tmpfs\",fstype!=\"overlay\"}))))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Disk I/O per second over last $__rate_interval minutes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{node=\"$node\",device!=\"lo\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{node=\"$node\",device!=\"lo\"}[$__rate_interval])",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "description": "Node mempool size",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "mmn_node_mempool_size{node=\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Time To Finality",
   "type": "timeseries",
   "description": "Average time to finalize transaction",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(mmn_node_time_to_finality_sum{node=\"$node\"}[$__rate_interval]) / rate(mmn_node_time_to_finality_count{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Transaction Tracker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "mmn_node_tracker_tx{node=\"$node\"}",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}