{
 "title": "MMN Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Basic Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "description": "Highest block height",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max (mmn_node_block_height)", "legendFormat": "Block Height" }
   ]
  },
  {
   "title": "Average Block Size",
   "type": "stat",
   "description": "Block average size over last $__rate_interval minutes",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mmn_node_block_size_bytes_sum[$__rate_interval])) / sum(rate(mmn_node_block_size_bytes_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions In Block",
   "type": "stat",
   "description": "Average transaction in each block over last $__rate_interval minutes",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mmn_node_tx_in_block_sum[$__range])) / sum(increase(mmn_node_tx_in_block_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Receive Transaction",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(mmn_node_received_client_tx_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Included in Block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg(increase(mmn_node_executed_tps_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executed TPS (Included In Block)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(mmn_node_executed_tps_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress TPS (Add to Mempool)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(mmn_node_ingress_tps_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(mmn_node_finalized_tps_count[$__range])) - (avg(rate(mmn_node_failed_tps_count[$__range])) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Transaction",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(mmn_node_failed_tps_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Reason",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (reason) (\r\n  increase(mmn_node_failed_tps_count{reason!=\"\"}[$__range])\r\n)\r\nor\r\nsum by (reason) (\r\n  label_replace(\r\n    increase(mmn_node_failed_tps_count{reason=\"\"}[$__range]),\r\n    \"reason\", \"other\", \"\", \"\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Panic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mmn_node_panic_count[$__range]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Invalid PoH",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mmn_node_invalid_poh_count[$__range]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Rejected Rate",
   "type": "timeseries",
   "description": "Rejected transaction rate over last ${__rate_interval} minutes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(mmn_node_rejected_tx_count[$__rate_interval])) / sum(rate(mmn_node_received_tx_count[$__rate_interval]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Rejected Reasons",
   "type": "piechart",
   "description": "Reasons for rejected transaction",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (reason) (increase(mmn_node_rejected_tx_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Ingress ",
   "type": "timeseries",
   "description": "Average ingress TPS over last ${__rate_interval} minutes",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg(rate(mmn_node_received_client_tx_count[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "timeseries",
   "description": "Duration between two consecutive block assemble",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mmn_node_block_time_sum[$__rate_interval]))\n/\nsum(rate(mmn_node_block_time_count[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Time To Finality",
   "type": "timeseries",
   "description": "Average time to finalize transaction",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mmn_node_time_to_finality_sum[$__rate_interval])) / sum(rate(mmn_node_time_to_finality_count[$__rate_interval]))",
     "legendFormat": "Time To Finality"
    }
   ]
  }
 ]
}