name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mmn:build .

      - name: Extract binary
        run: |
          id=$(docker create mmn:build)
          docker cp $id:/app/mmn ./mmn
          docker rm $id

      - name: Create Release
        uses: softprops/action-gh-release@v2 
        with:
          files: ./mmn
